chore: enable pre-commit for Rust formatting, pre-push for Rust linter check

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,14 +3,14 @@
 #pnpm pretty-quick --staged
 
 # 运行 clippy fmt
-#cargo fmt --manifest-path ./src-tauri/Cargo.toml
+cargo fmt --manifest-path ./src-tauri/Cargo.toml
 
-# if [ $? -ne 0 ]; then
-#     echo "rustfmt failed to format the code. Please fix the issues and try again."
-#     exit 1
-# fi
+if [ $? -ne 0 ]; then
+    echo "rustfmt failed to format the code. Please fix the issues and try again."
+    exit 1
+fi
 
-#git add .
+git add .
 
 # 允许提交
 exit 0
