chore: git hooks for linter and formatter

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,16 @@
+#!/bin/bash
+
 pnpm pretty-quick --staged
+
+# 运行 clippy fmt
+cargo fmt --manifest-path ./src-tauri/Cargo.toml
+
+if [ $? -ne 0 ]; then
+    echo "rustfmt failed to format the code. Please fix the issues and try again."
+    exit 1
+fi
+
+git add .
+
+# 允许提交
+exit 0
